### ISSUE TITLE
Automatically manufacture getters and setter

### ISSUE THREAD

**Issue by szepeviktor** [Ticketpark/SaferpayJsonApi#27]
There are a **lot** of getters and setters

```
$ grep -r ' function [gs]et' lib/ | wc -l
343
```

We could add annotations to properties and process get and set calls in `__call()`

**Comment by szepeviktor** [comment]
...and spare 343 function definitions

**Comment by sprain** [comment]
I am sceptical about this idea. I prefer obvious code over smart code.

**Comment by szepeviktor** [comment]
I also like explicit code.

**Comment by szepeviktor** [comment]
```php
<?php

declare(strict_types=1);

namespace Foo;

trait GetterSetter
{
    public function __call(string $name, array $arguments)
    {
        $method = substr($name, 0, 3);
        $property = lcfirst(substr($name, 3));

        if (! in_array($method, ['get', 'set'], true)) {
            throw new \Exception('Method does not exist');
        }

        if (! property_exists($this, $property)) {
            throw new \Exception('Property does not exist');
        }

        // TODO read annotations https://www.doctrine-project.org/projects/doctrine-annotations/en/latest/index.html

        switch ($method) {
            case 'get':
                return $this->{$property};
            case 'set':
                if (! array_key_exists(0, $arguments)) {
                    throw new \Exception('Argument is missing for setter');
                }
                $this->{$property} = $arguments[0];
                return $this;
        }

        // TODO pub/prot/priv method ??? same as prop???
    }
}
```

What do you think about it?

**Comment by sprain** [comment]
> What do you think about it?

I do not like it. Hard to read and you loose method name suggestions in IDEs. What would the user of the library gain by this?

**Comment by szepeviktor** [comment]
> What would the user of the library gain by this?

The library would drastically shrink in size;

**Comment by sprain** [comment]
> The library would drastically shrink in size;

That‘s no benefit for the user. Less code is not necessarily better code.

**Comment by szepeviktor** [comment]
Okay.

I'm working on this in a new package.

**Comment by sprain** [comment]
> I'm working on this in a new "GetterSetter" package.

Sure, go ahead. There might be other use cases where this makes sense. All the best to you!
