### ISSUE TITLE
JSON schema

### ISSUE THREAD

**Issue by szepeviktor** [Ticketpark/SaferpayJsonApi#31]
> > What do you think about creating a JSON schema for Saferpay API and generating our code/or automate things based on that?
>
> Yes, I thought about this, too. It would definitely make development simpler. It can still be added later without breaking a v3 release.

I would contribute to it and get you some money to work on it.

@sprain What do you think?

**Comment by sprain** [comment]
I appreciate the sentiment.

Still I have to ask now: what's your motivation to be so active on this library?

**Comment by szepeviktor** [comment]
My latest client (I work in long-term only) will switch to SIX.

**Comment by sprain** [comment]
I suppose, extracting the schema from this library would not be so hard by using some class reflection. Maybe as a start you can define what the schema eventually should look like with some examples?

**Comment by sprain** [comment]
There seems to be no more interest, therefore I close this.
