### ISSUE TITLE
Notification values seems to be not recognized by the API

### ISSUE THREAD

**Issue by syntaxys** [Ticketpark/SaferpayJsonApi#40]
As there's no example to set up an NotifyUrl I tried this:

$notification = new Container\Notification();
$notification->setNotifyUrl('https://domain.tld/success.php');
...
$initializeRequest = new InitializeRequest(
    $requestConfig,
    $terminalId,
    $payment,
    $returnUrls,
    $notification
);

No error occured during the transaction, but the URL isn't called from https://test.saferpay.com/
I tried to find out what's wrong, is there a way to debug it to file?

**Comment by sprain** [comment]
- Is your `domain.tld` actually publicly accessible? If it's a local dev domain, Saferpay cannot access it.
- I am not 100% sure whether Saferpay actually sends notifications in test environment.

**Comment by syntaxys** [comment]
This domain name ist just an example for explanation. If I use the right URL in $returnUrls then it works like a charm.
It seems like I missunderstood how to initiate the notifications, is it anywhere documented for that class?

**Comment by sprain** [comment]
> then it works like a charm

I do not understand the issue, then.

The library is based on https://saferpay.github.io/jsonapi/
Maybe https://www.six-payment-services.com/dam/saferpay/Saferpay_JSON_API_EN.pdf helps you out, too.

**Comment by sprain** [comment]
I will close this now. Feel free to re-open if you have new information regarding this library.
