### ISSUE TITLE
composer installs release 3.0.1 on a php 8 system

### ISSUE THREAD

**Issue by giriroub** [Ticketpark/SaferpayJsonApi#41]
If one requires the library on a php 8 system release 3.0.1 is installed, since it has the composer requirement
`"php": ">=7.3"`
This was changed for release 3.1 to 
`"php": "^7.3"`
which makes all later releases incompatible with php 8.
Can the library be made compatible with php 8?

**Comment by sprain** [comment]
PHP 8 is now officially supported by this library.
https://github.com/Ticketpark/SaferpayJsonApi/releases/tag/v3.3
