### ISSUE TITLE
from where should I get : terminalId

### ISSUE THREAD

**Issue by aboodalfar** [Ticketpark/SaferpayJsonApi#42]
![image](https://user-images.githubusercontent.com/57001511/119356031-a09e6a80-bcae-11eb-8983-2813c052d13d.png)

and customer id 👍 

![image](https://user-images.githubusercontent.com/57001511/119356149-c9266480-bcae-11eb-8db0-d522b599095f.png)

**Comment by sprain** [comment]
* `$customerId` is available in your contract with Saferpay.
* `$terminalId` can be found in your account on https://www.saferpay.com/BO/Settings/Terminal
