### ISSUE TITLE
Response view

### ISSUE THREAD

**Issue by onebeat** [Ticketpark/SaferpayJsonApi#47]
Hello, thank you very much for this script but i have 3 question.

- how can i get "full" reponse from AssertRequest class or CaptureRequest so i can get some more information ?
- in RecurringPayment where do i need to set $payment->setRecurring ?
- When i get redirect to success url i get transaction id from AssertRequest which i pass to Capture but then i get Transaction already captured, what i am doing wrong ?

Thank you very much for your answers.

**Comment by sprain** [comment]
* > how can i get "full" reponse from AssertRequest class or CaptureRequest so i can get some more information ?

You mean the raw response from Saferpay? The library does not provide this functionality. Howevery, you can get the raw response by outputting `$response->getBody()` in `Request::doExecute()`. [See here.](https://github.com/Ticketpark/SaferpayJsonApi/blob/026f004f23eaf831721c597045edc71143a19369/lib/SaferpayJson/Request/Request.php#L115)

* > in RecurringPayment where do i need to set $payment->setRecurring ?

This should work – but I personally have no experience with recurring payments:

```
$amount = new Container\Amount(5000,   'CHF');
$payment = new Container\Payment($amount);
$payment->setRecurring(new Container\Recurring());
// more payment settings
```

* > When i get redirect to success url i get transaction id from AssertRequest which i pass to Capture but then i get Transaction already captured, what i am doing wrong ?

Some ideas from the top of my mind:
* You are not using the correct transaction id?
* You are executing the same code more than once?
* You have some kind of auto-capturing enabled in your Saferpay account?

**Comment by onebeat** [comment]
Hello, thank you for your quick response. I have question about example code - why is there difference between code on github example folder (1-example-capture.php) and example folder when you install it via composer ?

**Comment by sprain** [comment]
>why is there difference between code on github example folder (1-example-capture.php) and example folder when you install it via composer ?

You are likely not installing the most recent version.

**Comment by onebeat** [comment]
I have installed it via composer require ticketpark/saferpay-json-api - what i am doing wrong ?
