### ISSUE TITLE
Error message: Transaction already captured

### ISSUE THREAD

**Issue by onebeat** [Ticketpark/SaferpayJsonApi#49]
> > When i get redirect to success url i get transaction id from AssertRequest which i pass to Capture but then i get Transaction already captured, what i am doing wrong ?
>  
> Some ideas from the top of my mind:
> * You are not using the correct token?
> * You are executing the same code more than once?
> * You have some kind of auto-capturing enabled in your Saferpay account?
> 
> _Originally posted by @sprain in https://github.com/Ticketpark/SaferpayJsonApi/issues/47#issuecomment-864537180_

I have tried any idea that i can thinkof - really don't know what to do else.

I have created "steps" for each part of Saferpay API, the last one CAPTURE is where we stucked. After geting TransactionId we have started capturing and we get this message TRANSACTION_ALREADY_CAPTURED

I have checked everything (double loading of CAPTURE script, disabling CAPTURE script so we can get TranscationId).

If the process of CAPTURE didn't happend from our side (where we get message TRANSACTION_ALREADY_CAPTURED) then in saferpay Journal it will be Pending and if we do it then in saferpay Journal it will be Capture.

I am developer for 12 years so i am always checking steps back to find bug, but now need your help if it possible...

**Comment by sprain** [comment]
I don't think we can help here without seeing your actual code.

**Comment by sprain** [comment]
I will close this now as no further information was provided. Feel free to re-open this issue if you have any news.
