### ISSUE TITLE
Request URLs contain a double slash

### ISSUE THREAD

**Issue by fabianerni** [Ticketpark/SaferpayJsonApi#68]
The Request class concatinates the Request::ROOT_URL constant with the API_PATH constant of the extending class, which results in a double slash in the URL.
saferpay.com seems to ignore this issue, but it may cause problems in case they will not accept such URLs in the future

Example
Request::ROOT_URL = '`https://www.saferpay.com/api/`'
AliasAssertInsertRequest::API_PATH = '`/Payment/v1/Alias/AssertInsert`'

Request::getURL() will combine this to
`https://www.saferpay.com/api//Payment/v1/Alias/AssertInsert`

**Comment by sprain** [comment]
Fixed in #69
