### ISSUE TITLE
Error on RequestExecute

### ISSUE THREAD

**Issue by lolzim** [Ticketpark/SaferpayJsonApi#8]
Hi,
Here is what I got:

> Fatal error: Uncaught exception 'Ticketpark\SaferpayJson\Exception\HttpRequestException' with message 'file_get_contents(https://test.saferpay.com/api//Payment/v1/PaymentPage/Initialize): failed to open stream: operation failed' in /var/www/site/vendor/ticketpark/saferpay-json-api/lib/SaferpayJson/Message/Request.php:188
Stack trace:
#0 /var/www/site/eshop/eshop.pay.php(262): Ticketpark\SaferpayJson\Message\Request->execute()
#1 {main}
  thrown in /data/zmodules_beta/vendor/ticketpark/saferpay-json-api/lib/SaferpayJson/Message/Request.php on line 188

/var/www/site/eshop/eshop.pay.php(262) is last line here:

`$response = (new InitializeRequest($apiKey, $apiSecret))`
`  ->setRequestHeader($requestHeader)`
`  ->setPayment($payment)`
`  ->setTerminalId($terminalId)`
`  ->setReturnUrls($returnUrls)`
`  ->setNotification($notification)`
`  ->execute();`

On script top I have
`use \Ticketpark\SaferpayJson\PaymentPage\InitializeRequest;`
`use \Ticketpark\SaferpayJson\Container;`
`use \Ticketpark\SaferpayJson\Message\ErrorResponse;`

I checked with ngrep, the connection to test.saferpay.com:443 happens.

What did I made wrong ?

Best regards

**Comment by lolzim** [comment]
Don't know exactly how, but I got the whole thing running at last.

**Comment by sprain** [comment]
This looks like a temporary glitch at Saferpay.
